# Generated by Django 5.1.6 on 2025-03-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
