# Generated by Django 5.1.6 on 2025-02-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
